In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.metrics        import confusion_matrix
from sklearn.metrics         import classification_report
from sklearn.metrics import accuracy_score

In [13]:

names= ['Sepal length','Sepal width', 'Petal length', 'Petal width', 'Flower class']
dataset= pd.read_csv("iris_data.txt", names=names)
dataset.head()

Sepal length  Sepal width  Petal length  Petal width  Flower class
0           5.1          3.5           1.4          0.2             1
1           4.9          3.0           1.4          0.2             1
2           4.7          3.2           1.3          0.2             1
3           4.6          3.1           1.5          0.2             1
4           5.0          3.6           1.4          0.2             1

In [17]:
dataset.isnull().values.any()

False

In [19]:
print(dataset.groupby('Flower class').size())

Flower class
1    50
2    50
3    50
dtype: int64


In [25]:
print(dataset.describe())

       Sepal length  Sepal width  Petal length  Petal width  Flower class
count    150.000000   150.000000    150.000000   150.000000    150.000000
mean       5.843333     3.054000      3.758667     1.198667      2.000000
std        0.828066     0.433594      1.764420     0.763161      0.819232
min        4.300000     2.000000      1.000000     0.100000      1.000000
25%        5.100000     2.800000      1.600000     0.300000      1.000000
50%        5.800000     3.000000      4.350000     1.300000      2.000000
75%        6.400000     3.300000      5.100000     1.800000      3.000000
max        7.900000     4.400000      6.900000     2.500000      3.000000


In [34]:
X=dataset.iloc[:,0:4]
y= dataset.iloc[:,4]
split_test_size=0.3

X_train,X_test,y_train,y_test= train_test_split(X,y, random_state=4,test_size=split_test_size)

In [41]:
knn_model_auto= KNeighborsClassifier()
knn_model_auto.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [55]:
knn_model_nb= KNeighborsClassifier(n_neighbors=11, p=3,metric='euclidean')
knn_model_nb.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=11, p=3,
           weights='uniform')

In [56]:
pred_train= knn_model_auto.predict(X_train)
print("Training accuracy when k=5,p=2: {0:.4%}".format(accuracy_score(y_train,pred_train)))
pred_train_nb= knn_model_nb.predict(X_train)
print("Training accuracy when k=11,p=3: {0:.4%}".format(accuracy_score(y_train,pred_train_nb)))

Training accuracy when k=5,p=2: 97.1429%
Training accuracy when k=11,p=3: 98.0952%


In [57]:
pred_test=knn_model_auto.predict(X_test)
pred_test_nb= knn_model_nb.predict(X_test)
print("Test accuracy when k=5,p=2: {0:.4%}".format(accuracy_score(y_test,pred_test)))
print("Test accuracy when k=11,p=3: {0:.4%}".format(accuracy_score(y_test,pred_test_nb)))

Test accuracy when k=5,p=2: 97.7778%
Test accuracy when k=11,p=3: 97.7778%


In [58]:
print(confusion_matrix(y_test,pred_test))

[[21  0  0]
 [ 0  9  1]
 [ 0  0 14]]


In [59]:
print(classification_report(y_test,pred_test))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00        21
          2       1.00      0.90      0.95        10
          3       0.93      1.00      0.97        14

avg / total       0.98      0.98      0.98        45

